CREATE DATABASE ess;
use ess
--Project Table Details
CREATE TABLE ESS.ESS_PROJ(PROJ_I INTEGER AUTO_INCREMENT PRIMARY KEY,
PROJ_N VARCHAR(50) NOT NULL,PROJ_DESC VARCHAR(100));


CREATE TABLE ESS.ESS_TMPLT(TMPLT_I INTEGER AUTO_INCREMENT PRIMARY KEY,
TMPLT_N VARCHAR(50) NOT NULL,TMPLT_DESC VARCHAR(100));


CREATE TABLE ESS.ESS_TMPLT_DETL(FLD_I INTEGER AUTO_INCREMENT PRIMARY KEY,
TMPLT_I INTEGER ,FLD_N VARCHAR(50) NOT NULL,FLD_DESC VARCHAR(50),
FOREIGN KEY (TMPLT_I) REFERENCES ESS_TMPLT(TMPLT_I)
);


CREATE TABLE ESS.ESS_PROJ_TMPLT(FLD_I INTEGER AUTO_INCREMENT PRIMARY KEY,
PROJ_I INTEGER,TMPL_I INTEGER,FLD_N VARCHAR(50),FLD_VAL_I INTEGER, 
FLD_VAL_T VARCHAR(50),
FOREIGN KEY (PROJ_I) REFERENCES ESS_PROJ(PROJ_I));


CREATE TABLE ESS.CODE_CATG(CODE_CATG_I INTEGER AUTO_INCREMENT PRIMARY KEY,
CODE_CATG_N VARCHAR(50) NOT NULL,CODE_CATG_DESC VARCHAR(50));


CREATE TABLE ESS.ESS_CODE(CODE_I INTEGER AUTO_INCREMENT PRIMARY KEY,
CODE_CATG_I INTEGER NOT NULL, CODE_VAL_N VARCHAR(50) NOT NULL,
CODE_VAL_DESC VARCHAR(50),
FOREIGN KEY (CODE_CATG_I) REFERENCES CODE_CATG(CODE_CATG_I)
);

--start mysqld
--mysqladmin -u root shutdown

